config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :home, only: %i[index show edit new create destroy]
  resources :posts
  resource :profiles,only: %i[show edit update]
  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  t.references :target, foreign_key: { to_table: :users }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :description, presence: true
  has_one_attached :thumbnail
  has_many :likes, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
       @posts = Post.all
    end

    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end
    
    def create
        @post = Post.new(post_params)
    
        if @post
          redirecto_to root_url
        else
          render :new
        end
      end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to root_url, notice: "Post was successfully destroyed."
    end
    
    private
    
    def post_params
        params.require(:post).permit(:description, :thumbnail)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def edit

    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
          redirect_to @post, notice: "Post was successfully updated."
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def show
        
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
    def error_messages(*objects)
        messages = objects.compact.map { |o| o.errors.full_messages }.flatten
        _error_messages(messages)
    end
  
    def _error_messages(messages)
        if messages.present?
            content_tag(:div, style: 'color: red') do
            list_items = messages.map { |m| content_tag(:li, m) }
            content_tag(:ul, safe_join(list_items), class: 'list-unstyled')
            end
        end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/views/home/index.html.erb
<div class="container max-w-5xl pt-8 mx-auto xl:grid xl:grid-cols-[630px_320px] xl:gap-16 md:pt-12">
  <div class="w-full mx-auto content">
    <div class="mx-auto w-[min(470px,100%)] divide-y divide-gray-300">
      <% @posts.each do |post| %>
        <article class="py-4">
          <div class="flex items-center py-3">
            <%= image_tag 'user.jpg', class: 'object-cover object-center w-8 h-8 rounded-full', width: "32", height: "32" %>
            <h2 class="ml-2 text-sm"><%= post.user.nickname %></h2>
            <time class="text-sm text-gray-500"><%= post.created_at.to_s(:human)%></time>
            <button class="ml-auto hover:opacity-60">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
              </svg>
            </button>
          </div>
          <%= image_tag 'ig-1.jpg', width: "4016", height: "6016" %>

          <div class="flex items-center py-2">
            <button class="grid w-10 h-10 -ml-2 place-items-center hover:opacity-60">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
              </svg>
            </button>
            <button class="grid w-10 h-10 place-items-center hover:opacity-60">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337z" />
              </svg>
            </button>
            <button class="grid w-10 h-10 place-items-center hover:opacity-60">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
              </svg>
            </button>
            <button class="grid w-10 h-10 ml-auto place-items-center hover:opacity-60">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" />
              </svg>
            </button>
          </div>
          <a class="block text-sm font-bold w-fit" href="#">いいね！95件</a>
          <p class="text-sm line-clamp-1">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ea explicabo
            deleniti repudiandae exercitationem similique. Veritatis temporibus dolore nostrum voluptates error.
            Commodi quisquam quae beatae dignissimos numquam amet delectus sapiente optio.</p>
          <button class="text-sm text-gray-500">続きを読む</button>
        </article>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New article</h1>

<%= form_with(model: @post) do |form| %>
  <%= error_messages(@post) %>

  <div>
  <%= form.label :thumbnail %>
  <%= form.file_field :thumbnail %>
</div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div>

  <% if @post.thumbnail.attached? %>
  <p>
    <strong>Thumbnail:</strong>
    <%= image_tag @post.thumbnail %>
  </p>
<% end %>
  <p>
    <strong>Content:</strong>
    
    <%= @post.description %>
  </p>
  <%= button_to '削除', post_path(@post), method: :delete %>
</div>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/profiles/show.html.erb
<div class="container max-w-[935px] mx-auto pt-12">
  <div class="grid grid-cols-[auto_1fr] items-start gap-7 px-4">
    <div class="md:p-7 py-7 md:row-span-2">
      <%= image_tag 'user.jpg', class: 'object-cover object-center w-16 h-16 rounded-full md:w-36 md:h-36' %>
    </div>
    <div class="grid grid-cols-[auto_1fr] w-fit gap-2 md:grid-cols-[auto_auto_auto_auto] items-center">
      <p class="text-lg"><%= current_user.nickname %></p>
      <button class="grid w-10 h-10 md:order-3 place-items-center"><svg xmlns="http://www.w3.org/2000/svg"
          fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round"
            d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
      </button>

    <%= link_to 'プロフィールを編集', edit_user_registration_path, class: "col-span-2 px-4 py-2 text-sm font-bold leading-none text-center bg-gray-200 rounded-md md:col-span-1 w-60 md:w-fit"%>
      <button
        class="col-span-2 px-4 py-2 text-sm font-bold leading-none text-center bg-gray-200 rounded-md md:col-span-1 w-60 md:w-fit">広告ツール</button>
    </div>
    <div class="col-span-2 md:col-span-1 md:col-start-2">
      <div class="hidden gap-10 md:flex">
        <p>投稿<strong>173</strong>件</p>
        <p>フォロワー<strong>227</strong>人</p>
        <p>フォロー中<strong>287</strong>人</p>
      </div>
      <p class="text-sm font-bold md:mt-4">HOGEHOGE</p>
      <p class="text-sm">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ea explicabo deleniti
        repudiandae
        exercitationem similique. Veritatis temporibus dolore nostrum voluptates error. Commodi quisquam quae
        beatae
        dignissimos numquam amet delectus sapiente optio.</p>
    </div>
  </div>
  <div class="grid grid-cols-3 gap-10 py-2 mt-4 text-sm border-t border-gray-200 md:hidden">
    <p class="text-center">投稿<br><strong>173</strong><br>件</p>
    <p class="text-center">フォロワー<br><strong>227</strong><br>人</p>
    <p class="text-center">フォロー中<br><strong>287</strong><br>人</p>
  </div>
  <div class="md:px-4">
    <div
      class="grid justify-center grid-cols-3 border-t border-gray-200 justify-items-stretch md:flex md:gap-14 md:mt-8">
      <button
        class="flex items-center justify-center gap-2 -translate-y-px border-t border-gray-600 h-14 text-sky-600 md:text-gray-600">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
          stroke="currentColor" class="w-6 h-6 md:h-4 md:w-4">
          <path stroke-linecap="round" stroke-linejoin="round"
            d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zM3.75 15.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zM13.5 15.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z" />
        </svg>
        <span class="hidden text-xs font-bold md:inline">投稿</span>
      </button>
      <button class="flex items-center justify-center gap-2 text-gray-500 -translate-y-px h-14">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
          stroke="currentColor" class="w-6 h-6 md:h-4 md:w-4">
          <path stroke-linecap="round" stroke-linejoin="round"
            d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" />
        </svg>
        <span class="hidden text-xs font-bold md:inline">保存済み</span>
      </button>
      <button class="flex items-center justify-center gap-2 text-gray-500 -translate-y-px h-14">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
          stroke="currentColor" class="w-6 h-6 md:h-4 md:w-4">
          <path stroke-linecap="round" stroke-linejoin="round"
            d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
        </svg>
        <span class="hidden text-xs font-bold md:inline">タグ付けされている人</span>
      </button>
    </div>
  </div>
  <div class="grid grid-cols-3 gap-1 md:px-4">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-1.jpg" width="4016" height="6016"
      alt="">
    <img class="object-cover object-center aspect-square" src="/img/instagram/ig-2.jpg" width="5438" height="3625"
      alt="">
  </div>
</div>